services:
  - type: web
    name: shipnest-web
    runtime: docker
    plan: starter
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: ShipNest
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: shipnest-redis
          property: connectionString
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: SCOUT_DRIVER
        value: collection
      - key: BROADCAST_CONNECTION
        value: log
      - key: RUN_MIGRATIONS
        value: "true"

  - type: worker
    name: shipnest-worker
    runtime: docker
    plan: starter
    dockerCommand: php artisan queue:work database --sleep=3 --tries=3 --max-time=3600
    envVars:
      - key: APP_NAME
        value: ShipNest
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: shipnest-redis
          property: connectionString
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: FILESYSTEM_DISK
        value: local
      - key: SCOUT_DRIVER
        value: collection
      - key: BROADCAST_CONNECTION
        value: log
      - key: RUN_MIGRATIONS
        value: "false"

  - type: keyvalue
    name: shipnest-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
