<?php

return [
    'openai' => [
        'label' => 'OpenAI',
        'tagline' => 'Recommended for stable chat',
        'driver' => 'openai_compatible',
        'base_url' => 'https://api.openai.com/v1',
        'default_model' => 'gpt-4o-mini',
        'default_vision_model' => 'gpt-4o-mini',
        'models' => [
            'gpt-4o-mini' => 'GPT-4o Mini',
            'gpt-4o' => 'GPT-4o',
            'gpt-4.1' => 'GPT-4.1',
            'gpt-4.1-mini' => 'GPT-4.1 Mini',
            'o1-mini' => 'o1-mini',
        ],
        'vision_models' => [
            'gpt-4o-mini' => 'GPT-4o Mini',
            'gpt-4o' => 'GPT-4o',
            'gpt-4.1' => 'GPT-4.1',
            'gpt-4.1-mini' => 'GPT-4.1 Mini',
        ],
        'supports_vision' => true,
        'icon' => 'O',
        'icon_bg' => '#10a37f',
    ],
    'openrouter' => [
        'label' => 'OpenRouter',
        'tagline' => 'Recommended for flexible model routing',
        'driver' => 'openai_compatible',
        'base_url' => 'https://openrouter.ai/api/v1',
        'default_model' => 'openai/gpt-4o-mini',
        'default_vision_model' => 'openai/gpt-4o-mini',
        'models' => [
            'openai/gpt-4o-mini' => 'OpenAI GPT-4o Mini',
            'openai/gpt-4o' => 'OpenAI GPT-4o',
            'anthropic/claude-3.5-haiku' => 'Claude 3.5 Haiku',
            'google/gemini-2.0-flash-001' => 'Gemini 2.0 Flash',
            'meta-llama/llama-3.3-70b-instruct' => 'Llama 3.3 70B',
        ],
        'vision_models' => [
            'openai/gpt-4o-mini' => 'OpenAI GPT-4o Mini',
            'openai/gpt-4o' => 'OpenAI GPT-4o',
            'google/gemini-2.0-flash-001' => 'Gemini 2.0 Flash',
        ],
        'supports_vision' => true,
        'icon' => 'OR',
        'icon_bg' => '#6366f1',
    ],
    'anthropic' => [
        'label' => 'Anthropic',
        'tagline' => 'Strong reasoning and business writing',
        'driver' => 'anthropic',
        'base_url' => 'https://api.anthropic.com/v1',
        'default_model' => 'claude-3-5-haiku-latest',
        'default_vision_model' => 'claude-3-5-haiku-latest',
        'models' => [
            'claude-3-5-haiku-latest' => 'Claude 3.5 Haiku',
            'claude-3-5-sonnet-latest' => 'Claude 3.5 Sonnet',
            'claude-3-opus-latest' => 'Claude 3 Opus',
            'claude-3-haiku-20240307' => 'Claude 3 Haiku',
        ],
        'vision_models' => [
            'claude-3-5-haiku-latest' => 'Claude 3.5 Haiku',
            'claude-3-5-sonnet-latest' => 'Claude 3.5 Sonnet',
            'claude-3-opus-latest' => 'Claude 3 Opus',
        ],
        'supports_vision' => true,
        'icon' => 'A',
        'icon_bg' => '#d97757',
    ],
    'gemini' => [
        'label' => 'Google Gemini',
        'tagline' => 'Fast multilingual chat',
        'driver' => 'gemini',
        'base_url' => 'https://generativelanguage.googleapis.com/v1beta',
        'default_model' => 'gemini-2.0-flash',
        'default_vision_model' => 'gemini-2.0-flash',
        'models' => [
            'gemini-2.0-flash' => 'Gemini 2.0 Flash',
            'gemini-2.0-flash-lite' => 'Gemini 2.0 Flash Lite',
            'gemini-1.5-flash' => 'Gemini 1.5 Flash',
            'gemini-1.5-pro' => 'Gemini 1.5 Pro',
        ],
        'vision_models' => [
            'gemini-2.0-flash' => 'Gemini 2.0 Flash',
            'gemini-2.0-flash-lite' => 'Gemini 2.0 Flash Lite',
            'gemini-1.5-flash' => 'Gemini 1.5 Flash',
            'gemini-1.5-pro' => 'Gemini 1.5 Pro',
        ],
        'supports_vision' => true,
        'icon' => 'G',
        'icon_bg' => '#4285f4',
    ],
    'groq' => [
        'label' => 'Groq',
        'tagline' => 'Very fast responses',
        'driver' => 'openai_compatible',
        'base_url' => 'https://api.groq.com/openai/v1',
        'default_model' => 'llama-3.3-70b-versatile',
        'default_vision_model' => 'llama-3.2-11b-vision-preview',
        'models' => [
            'llama-3.3-70b-versatile' => 'Llama 3.3 70B',
            'llama-3.1-8b-instant' => 'Llama 3.1 8B Instant',
            'mixtral-8x7b-32768' => 'Mixtral 8x7B',
            'gemma2-9b-it' => 'Gemma 2 9B',
        ],
        'vision_models' => [
            'llama-3.2-11b-vision-preview' => 'Llama 3.2 11B Vision',
            'llama-3.2-90b-vision-preview' => 'Llama 3.2 90B Vision',
        ],
        'supports_vision' => true,
        'icon' => 'GQ',
        'icon_bg' => '#f55036',
    ],
    'deepseek' => [
        'label' => 'DeepSeek',
        'tagline' => 'Low-cost strong text model',
        'driver' => 'openai_compatible',
        'base_url' => 'https://api.deepseek.com/v1',
        'default_model' => 'deepseek-chat',
        'default_vision_model' => 'deepseek-chat',
        'models' => [
            'deepseek-chat' => 'DeepSeek Chat',
            'deepseek-reasoner' => 'DeepSeek Reasoner',
        ],
        'vision_models' => [],
        'supports_vision' => false,
        'icon' => 'DS',
        'icon_bg' => '#2563eb',
    ],
    'mistral' => [
        'label' => 'Mistral AI',
        'tagline' => 'European text model option',
        'driver' => 'openai_compatible',
        'base_url' => 'https://api.mistral.ai/v1',
        'default_model' => 'mistral-small-latest',
        'default_vision_model' => 'pixtral-12b-latest',
        'models' => [
            'mistral-small-latest' => 'Mistral Small',
            'mistral-large-latest' => 'Mistral Large',
            'open-mistral-nemo' => 'Mistral Nemo',
            'codestral-latest' => 'Codestral',
        ],
        'vision_models' => [
            'pixtral-12b-latest' => 'Pixtral 12B',
            'pixtral-large-latest' => 'Pixtral Large',
        ],
        'supports_vision' => true,
        'icon' => 'M',
        'icon_bg' => '#f97316',
    ],
    'cohere' => [
        'label' => 'Cohere',
        'tagline' => 'Good for enterprise text and RAG',
        'driver' => 'openai_compatible',
        'base_url' => 'https://api.cohere.com/compatibility/v1',
        'default_model' => 'command-r-plus-08-2024',
        'default_vision_model' => 'command-r-plus-08-2024',
        'models' => [
            'command-r-plus-08-2024' => 'Command R+',
            'command-r-08-2024' => 'Command R',
            'command-light' => 'Command Light',
        ],
        'vision_models' => [],
        'supports_vision' => false,
        'icon' => 'C',
        'icon_bg' => '#39594d',
    ],
    'azure_openai' => [
        'label' => 'Azure OpenAI',
        'tagline' => 'Enterprise OpenAI through Azure',
        'driver' => 'openai_compatible',
        'base_url' => '',
        'default_model' => 'gpt-4o-mini',
        'default_vision_model' => 'gpt-4o-mini',
        'models' => [
            'gpt-4o-mini' => 'GPT-4o Mini',
            'gpt-4o' => 'GPT-4o',
            'gpt-4.1' => 'GPT-4.1',
            'gpt-4.1-mini' => 'GPT-4.1 Mini',
        ],
        'vision_models' => [
            'gpt-4o-mini' => 'GPT-4o Mini',
            'gpt-4o' => 'GPT-4o',
            'gpt-4.1' => 'GPT-4.1',
        ],
        'supports_vision' => true,
        'requires_base_url' => true,
        'icon' => 'Az',
        'icon_bg' => '#0078d4',
    ],
    'bedrock' => [
        'label' => 'AWS Bedrock',
        'tagline' => 'Enterprise AWS-hosted models',
        'driver' => 'openai_compatible',
        'base_url' => '',
        'default_model' => 'anthropic.claude-3-haiku-20240307-v1:0',
        'default_vision_model' => 'anthropic.claude-3-haiku-20240307-v1:0',
        'models' => [
            'anthropic.claude-3-haiku-20240307-v1:0' => 'Claude 3 Haiku',
            'anthropic.claude-3-sonnet-20240229-v1:0' => 'Claude 3 Sonnet',
            'anthropic.claude-3-5-sonnet-20240620-v1:0' => 'Claude 3.5 Sonnet',
            'meta.llama3-70b-instruct-v1:0' => 'Llama 3 70B',
        ],
        'vision_models' => [
            'anthropic.claude-3-haiku-20240307-v1:0' => 'Claude 3 Haiku',
            'anthropic.claude-3-sonnet-20240229-v1:0' => 'Claude 3 Sonnet',
            'anthropic.claude-3-5-sonnet-20240620-v1:0' => 'Claude 3.5 Sonnet',
        ],
        'supports_vision' => true,
        'requires_base_url' => true,
        'icon' => 'BR',
        'icon_bg' => '#ff9900',
    ],
    'ollama' => [
        'label' => 'Ollama (self-hosted)',
        'tagline' => 'Local/self-hosted models',
        'driver' => 'openai_compatible',
        'base_url' => 'http://127.0.0.1:11434/v1',
        'default_model' => 'llama3.2',
        'default_vision_model' => 'llava',
        'models' => [
            'llama3.2' => 'Llama 3.2',
            'llama3.1' => 'Llama 3.1',
            'mistral' => 'Mistral',
            'phi3' => 'Phi-3',
            'gemma2' => 'Gemma 2',
        ],
        'vision_models' => [
            'llava' => 'LLaVA',
            'llama3.2-vision' => 'Llama 3.2 Vision',
        ],
        'supports_vision' => true,
        'requires_base_url' => true,
        'icon' => 'Ol',
        'icon_bg' => '#111827',
    ],
    'github_models' => [
        'label' => 'GitHub Models',
        'tagline' => 'Azure-hosted models via GitHub token',
        'driver' => 'openai_compatible',
        'base_url' => 'https://models.inference.ai.azure.com',
        'default_model' => 'gpt-4o-mini',
        'default_vision_model' => 'gpt-4o-mini',
        'models' => [
            'gpt-4o-mini' => 'GPT-4o Mini',
            'gpt-4o' => 'GPT-4o',
            'gpt-4.1' => 'GPT-4.1',
            'gpt-4.1-mini' => 'GPT-4.1 Mini',
            'Phi-4' => 'Phi-4',
            'Phi-3.5-mini-instruct' => 'Phi-3.5 Mini',
            'Mistral-large' => 'Mistral Large',
            'Mistral-small' => 'Mistral Small',
            'Llama-3.3-70B-Instruct' => 'Llama 3.3 70B',
        ],
        'vision_models' => [
            'gpt-4o-mini' => 'GPT-4o Mini',
            'gpt-4o' => 'GPT-4o',
            'gpt-4.1' => 'GPT-4.1',
            'gpt-4.1-mini' => 'GPT-4.1 Mini',
        ],
        'supports_vision' => true,
        'icon' => 'GH',
        'icon_bg' => '#24292f',
        'env_api_key' => 'GITHUB_TOKEN',
        'env_base_url' => 'GITHUB_MODELS_ENDPOINT',
    ],
];
